### ISSUE TITLE
Wrong time in posts for Brazilian timezones

### ISSUE THREAD

**Issue by dantepippi** [mattermost/mattermost-server#12920]
Brazil cancelled Daylight Saving Time (DST) for 2019 (that is uncertain for next years), so I can't get my server to display the correct time on posts and e-mails. 

Steps to reproduce:
- Set server with correct date/time
- Send post and check the wrong time (+1hour)
or 
- Set server with correct date/time
- Set  "ExperimentalTimezone": true
- Set timezone in Mattermost to America/Sao_Paulo (or others in Brazil)
- Send post and check the wrong time (+1hour)

**Comment by amyblais** [comment]
@dantepippi What Mattermost server version, device and OS & version are you using?

**Comment by dantepippi** [comment]
Hello @amyblais ! 
I've verified this behavior on server version 5.16.1 and windows desktop clients version 4.2.3.
Thanks for your time!

**Comment by amyblais** [comment]
@dantepippi We fixed a bug in v4.3.0 desktop app version related to timezone issues
 - Bug ticket: https://mattermost.atlassian.net/browse/MM-14168
 - Issue report: https://github.com/mattermost/desktop/issues/679

I'm wondering if you'd be open to updating to v4.3.1 to see if that fixes the issue? Note that there are some known issues in v4.3.1 that we are working on fixing: https://docs.mattermost.com/help/apps/desktop-changelog.html#release-v4-3-0

**Comment by dantepippi** [comment]
I'm sorry, @amyblais . I didn't realize there was a new version of the desktop client (would be nice to have a version check option). 
Updating to 4.3.1 fixed the issue.

**Comment by amyblais** [comment]
No worries, awesome to hear that the issue got resolved!

**Comment by nickolasdeluca** [comment]
Updating the app to v4.3.0 fixed the issue, until today, it is now displaying 1 hour forward again.
I even tried to update to v4.3.1 and it still doesnt properly show the timestamp.
Any ideas? I'm also from Brasil by the way.
