### ISSUE TITLE
Boards: Emoji Mart™ picker empty / not showing any emojis

### ISSUE THREAD

**Issue by maltem-za** [mattermost/mattermost-server#23397]
#### Summary
![mattermost-boards-emoji-picker-empty](https://github.com/mattermost/mattermost-server/assets/1404980/0a1a2222-c59a-436d-8e10-de0308cc3f64)

#### Steps to reproduce
Mattermost Team Edition 7.8.3 with Boards 7.10.0
Desktop client 5.3.1 on Windows 10 (same behaviour when using a browser)

#### Observed behavior (that appears unintentional) 
"Developer Tools for Current Server" in the desktop client shows a 404 for https://domain/static/emoji_spirit.png

#### Additional information
This MM instance is running as part of a GitLab Omnibus installation. Presumably I could drop the missing file in the appropriate place on the server, except that it doesn't seem to exist anywhere in the public repos.

**Comment by maltem-za** [comment]
@amyblais Any idea where I might find the PNG file?

**Comment by amyblais** [comment]
> Any idea where I might find the PNG file?

I'll add @sbishel here in case he knows.

**Comment by sbishel** [comment]
Should have been included in 7.10, it's here though.

https://github.com/mattermost/focalboard/blob/main/webapp/static/emoji_spirit.png

**Comment by maltem-za** [comment]
Thank you! Strangely the file does already exist in these two locations: `/var/opt/gitlab/mattermost/plugins/focalboard/webapp/dist` and `/var/opt/gitlab/mattermost/plugins/focalboard/pack/static`

So unfortunately not as simple a solution as I had thought... ¯\\_(ツ)_/¯

**Comment by maltem-za** [comment]
FYI the problem was resolved after upgrading our GitLab Omnibus installation to 15.11.6, which updated Mattermost to 7.9.2. When viewing Boards the version shown in the top right corner is now 7.9.3 (which is a bit confusing, but oh well...).

**Comment by cybertschunk** [comment]
will there be a backport for this fix to the 7.8 ESR release?

**Comment by sbishel** [comment]
@cybertschunk - We can backport, as I'm just getting ready to do a new dot release for v7.8.

**Comment by cybertschunk** [comment]
Thanks, that would be awesome sone we are facing the issue as well and canˋt upgrade to a new major release any time soon.

**Comment by cybertschunk** [comment]
Hello, unfortunately the issue still exists in v7.8.6 the call to `/static/emoji_spirit.png` returns a 404 error in the dev tools.

**Comment by amyblais** [comment]
The fix hasn't been backported quite yet.

**Comment by amyblais** [comment]
v7.8.7 is now available and includes the fix.
