### ISSUE TITLE
Flickering of login page after initial login in a separate tab

### ISSUE THREAD

**Issue by petahbred** [mattermost/mattermost-server#8398]
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
The login page appears for a short amount of time after logging in and creating a new tab.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
1. Log into mattermost.
1. Open a new tab
1. Navigate to the mattermost url.

* Version: 4.7.0
* Make sure cache is enabled ( `disable cache` is unchecked )

#### Expected behavior
Login page not to appear since the user is already logged in.

#### Observed behavior (that appears unintentional) 
Login page appears for a brief moment, even if the user is already logged in.
![screenshot](https://user-images.githubusercontent.com/1300226/36928923-62f86f98-1e3f-11e8-9262-d7c89ad45073.jpg)

**Comment by koxen** [comment]
I am pretty sure it was fixed on master

**Comment by psrivongse** [comment]
@koxen would you be able to point me at the commit? Scouring through I'm not able to find where the change took place.
Much Appreciated

**Comment by koxen** [comment]
https://github.com/mattermost/mattermost-webapp/pull/685

**Comment by psrivongse** [comment]
Thanks! Appreciated.

**Comment by petahbred** [comment]
v4.9.0 still experiencing this issue on Chrome, Firefox, and Safari. Using nginx in front of mattermost.

**Comment by lindy65** [comment]
Hi @petahbred,

Can you try reproducing your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) with your set-up as I'm not able to reproduce it on Chrome or Firefox.

**Comment by lindy65** [comment]
Hi @petahbred,

OK to close off this issue now?  Is it still reproducing for you on our nightly build server (linked above)?

**Comment by amyblais** [comment]
Hi @petahbred , we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
